repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        # MyPy needs to run on all files, not just staged ones.
        # For example, changing the type hint in one file
        # may affect typing correctness in another unchanged file.
        args: ["."]
        pass_filenames: false      
        exclude: "^tests/"
        additional_dependencies: [
          "types-pytz",
          "types-redis"
        ]